### ISSUE TITLE
About the Direction of Input Image 

### ISSUE THREAD

**Issue by Mors20** [AImageLab-zip/ToothFairy#12]
Dear Organizers,

I have a question regarding the direction of the input image. When our algorithm is evaluated on the Grand Challenge platform, we receive a single image, **SimpleITK.Image**, as input. I am curious if the direction information stored in this **SimpleITK.Image** is physically accurate. I have observed that all images in the dataset are in the 'RAI' direction. Are there any images in different directions for the Final Test Phase? If such images exist, will the direction information be stored accurately in the **SimpleITK.Image**. Understanding this aspect is essential for ensuring our algorithm functions correctly.

I look forward to your reply. Thank you!

Best regards,
Haoshen

**Comment by prittt** [comment]
Dear @Mors20, 

Yes, the metadata is physically accurate and will be so in the test set as well. Anyway, all images in the test set will have the same direction.

Best regards, 
Federico.
