### ISSUE TITLE
'gt' 'pred' in evaluation

### ISSUE THREAD

**Issue by ff741333** [AImageLab-zip/ToothFairy#7]
I found the order of variables 'gt' 'pred' in  [evaluation](https://github.com/AImageLab-zip/ToothFairy/blob/main/ToothFairy2/evaluation/evaluation.py) was wrong.

line 111 `def compute_multiclass_dice_and_hd95(pred, label):`
line 175 `dice, hd95 = compute_multiclass_dice_and_hd95(gt, pred)`

**Comment by LucaLumetti** [comment]
Hi @ff741333,

Thank you for pointing that out! Fortunately, both the Dice and HD95 metrics are commutative, meaning that the results remain the same regardless of the order of the parameters.

However, I'll go ahead and make the change to avoid any potential confusion.

Best regards,
Luca
